[phases.setup]
nixPkgs = ['python310', 'gdal', 'geos', 'proj', 'postgresql']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --settings=ankavidange.settings_production']

[start]
cmd = 'python manage.py migrate --settings=ankavidange.settings_production && gunicorn --bind 0.0.0.0:$PORT ankavidange.wsgi:application'
