[phases.setup]
nixPkgs = ['python312', 'python312Packages.pip', 'postgresql']

[phases.install]
# Ensure pip exists in the environment, then install
cmds = [
  'python3.12 -m ensurepip --upgrade || true',
  'python3.12 -m pip install --upgrade pip setuptools wheel',
  'python3.12 -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['python3.12 manage.py collectstatic --noinput --settings=ankavidange.settings_production']

[start]
cmd = 'python3.12 manage.py migrate --settings=ankavidange.settings_production && gunicorn --bind 0.0.0.0:$PORT ankavidange.wsgi:application'
