# Generated by Django 5.2.5 on 2025-09-07 00:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankavidangeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='volume_traite',
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='type',
            field=models.CharField(choices=[('PERSONNE_PHYSIQUE', 'Personne physique'), ('PERSONNE_MORALE', 'Personne morale')], default='PERSONNE_PHYSIQUE', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='vidangeurmecanique',
            name='stationnement',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='position géographique'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='token FCM')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10, verbose_name='plateforme')),
                ('app_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='version app')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernier contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appareil',
                'verbose_name_plural': 'appareils',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='ankavidange_user_id_421b15_idx')],
            },
        ),
    ]
