# Generated by Django 5.2.5 on 2025-09-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankavidangeapp', '0002_remove_demande_date_debut_remove_demande_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrevidange',
            name='type',
            field=models.CharField(choices=[('STBV', 'STBV'), ('TEMPORAIRE', 'Temporaire')], default='STBV', max_length=20, verbose_name='type de centre'),
        ),
    ]
