# Generated by Django 5.2.5 on 2025-09-15 14:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankavidangeapp', '0003_centrevidange_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom du stationnement')),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='position géographique')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='vidangeurmecanique',
            name='stationnement',
        ),
        migrations.AddField(
            model_name='vidangeur',
            name='stationnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidangeurs', to='ankavidangeapp.stationnement', verbose_name='stationnement'),
        ),
    ]
